export const priceTrendData = [
  { date: "Jan 20", price: 245 },
  { date: "Jan 21", price: 268 },
  { date: "Jan 22", price: 289 },
  { date: "Jan 23", price: 312 },
  { date: "Jan 24", price: 298 },
  { date: "Jan 25", price: 275 },
  { date: "Jan 26", price: 256 },
  { date: "Jan 27", price: 234 },
  { date: "Jan 28", price: 267 },
  { date: "Jan 29", price: 289 },
  { date: "Jan 30", price: 301 },
  { date: "Jan 31", price: 278 },
  { date: "Feb 1", price: 265 },
  { date: "Feb 2", price: 245 },
];

export interface Flight {
  id: string;
  airline: string;
  logo: string;
  departureTime: string;
  arrivalTime: string;
  origin: string;
  destination: string;
  duration: string;
  stops: number;
  price: number;
  class: string;
}

export const mockFlights: Flight[] = [
  {
    id: "1",
    airline: "United Airlines",
    logo: "UA",
    departureTime: "08:00 AM",
    arrivalTime: "11:30 AM",
    origin: "JFK",
    destination: "LAX",
    duration: "5h 30m",
    stops: 0,
    price: 245,
    class: "Economy",
  },
  {
    id: "2",
    airline: "Delta",
    logo: "DL",
    departureTime: "10:15 AM",
    arrivalTime: "02:00 PM",
    origin: "JFK",
    destination: "LAX",
    duration: "5h 45m",
    stops: 0,
    price: 289,
    class: "Economy",
  },
  {
    id: "3",
    airline: "American Airlines",
    logo: "AA",
    departureTime: "12:30 PM",
    arrivalTime: "04:15 PM",
    origin: "JFK",
    destination: "LAX",
    duration: "5h 45m",
    stops: 0,
    price: 312,
    class: "Economy",
  },
  {
    id: "4",
    airline: "JetBlue",
    logo: "B6",
    departureTime: "02:45 PM",
    arrivalTime: "06:30 PM",
    origin: "JFK",
    destination: "LAX",
    duration: "5h 45m",
    stops: 0,
    price: 198,
    class: "Economy",
  },
  {
    id: "5",
    airline: "Southwest",
    logo: "WN",
    departureTime: "06:00 AM",
    arrivalTime: "11:15 AM",
    origin: "JFK",
    destination: "LAX",
    duration: "7h 15m",
    stops: 1,
    price: 167,
    class: "Economy",
  },
  {
    id: "6",
    airline: "United Airlines",
    logo: "UA",
    departureTime: "07:30 AM",
    arrivalTime: "01:45 PM",
    origin: "JFK",
    destination: "LAX",
    duration: "8h 15m",
    stops: 1,
    price: 189,
    class: "Economy",
  },
  {
    id: "7",
    airline: "Spirit Airlines",
    logo: "NK",
    departureTime: "09:00 AM",
    arrivalTime: "03:30 PM",
    origin: "JFK",
    destination: "LAX",
    duration: "8h 30m",
    stops: 2,
    price: 145,
    class: "Economy",
  },
  {
    id: "8",
    airline: "Alaska Airlines",
    logo: "AS",
    departureTime: "01:00 PM",
    arrivalTime: "04:45 PM",
    origin: "JFK",
    destination: "LAX",
    duration: "5h 45m",
    stops: 0,
    price: 278,
    class: "Economy",
  },
  {
    id: "9",
    airline: "Frontier",
    logo: "F9",
    departureTime: "05:30 AM",
    arrivalTime: "02:15 PM",
    origin: "JFK",
    destination: "LAX",
    duration: "10h 45m",
    stops: 2,
    price: 129,
    class: "Economy",
  },
  {
    id: "10",
    airline: "Spirit Airlines",
    logo: "NK",
    departureTime: "11:45 PM",
    arrivalTime: "10:30 AM",
    origin: "JFK",
    destination: "LAX",
    duration: "12h 45m",
    stops: 3,
    price: 99,
    class: "Economy",
  },
];

export const airlines = [
  "United Airlines",
  "Delta",
  "American Airlines",
  "JetBlue",
  "Southwest",
  "Spirit Airlines",
  "Alaska Airlines",
];
